services:
  postgres:
    image: postgres:16
    container_name: tertulias_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: tertulias_db
    ports:
      - "5433:5432"
    volumes:
      - tertulias_postgres_data:/var/lib/postgresql/data

volumes:
  tertulias_postgres_data:
